"""
389. Find the Difference
Solved
Easy
Topics
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""

import string
from typing import List
from collections import defaultdict

# Definition for singly-linked list.
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

class Solution:
    def leetcode(self, s: str, t: str) -> str:
        ls = list(s)
        lt = list(t)
        # print(ls)
        # print(lt)
        ls.sort()
        lt.sort()
        lls = len(ls)
        llt = len(lt)
        for ii in range(lls):
            if ls[ii] != lt[ii]:
                return lt[ii]
        return lt[-1]

if __name__ == "__main__":
    app = Solution()
    a = "hello"
    a = " "
    a = [4, 9, 5]
    b = [9, 4, 9, 8, 4]
    print(app.leetcode(a,b))
